# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

remote_write:
- url: http://cortex:9009/api/prom/push

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'loki'
    static_configs:
    - targets: ['loki:3100']
  - job_name: 'promtail'
    static_configs:
    - targets: ['promtail:9080']